In [2]:
df=pd.read_csv('penguins.csv')

In [3]:
df.head()

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [4]:
df.isnull().sum()

id                    0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [5]:
df.drop(['id','year'],axis=1,inplace=True)

In [6]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female

In [7]:
df.isna().sum()
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female

In [8]:
df['bill_length_mm'].median()

np.float64(44.45)

In [9]:
df['bill_length_mm'].unique()

array([39.1, 39.5, 40.3,  nan, 36.7, 39.3, 38.9, 39.2, 34.1, 42. , 37.8,
       41.1, 38.6, 34.6, 36.6, 38.7, 42.5, 34.4, 46. , 37.7, 35.9, 38.2,
       38.8, 35.3, 40.6, 40.5, 37.9, 37.2, 40.9, 36.4, 42.2, 37.6, 39.8,
       36.5, 40.8, 36. , 44.1, 37. , 39.6, 37.5, 42.3, 40.1, 35. , 34.5,
       41.4, 39. , 35.7, 41.3, 41.6, 35.5, 41.8, 33.5, 39.7, 45.8, 42.8,
       36.2, 42.1, 42.9, 35.1, 37.3, 36.3, 36.9, 38.3, 34. , 38.1, 33.1,
       43.2, 41. , 45.6, 42.7, 40.2, 35.2, 41.5, 38.5, 43.1, 36.8, 35.6,
       32.1, 40.7, 46.1, 50. , 48.7, 47.6, 46.5, 45.4, 46.7, 43.3, 46.8,
       49. , 45.5, 48.4, 49.3, 49.2, 46.2, 50.2, 45.1, 46.3, 44.5, 47.8,
       48.2, 47.3, 59.6, 49.1, 42.6, 44.4, 44. , 49.6, 45.3, 50.5, 43.6,
       44.9, 45.2, 46.6, 48.5, 50.1, 45. , 43.8, 50.4, 45.7, 54.3, 49.8,
       49.5, 43.5, 50.7, 47.7, 46.4, 48.6, 47.5, 51.1, 52.5, 47.4, 50.8,
       43.4, 51.3, 52.1, 52.2, 49.4, 46.9, 55.9, 47.2, 41.7, 53.4, 48.1,
       51.5, 55.1, 48.8, 49.9, 52.7, 51.7, 47. , 52. , 45.9, 50.3, 58. ,
       42.4, 50.6, 52.8, 54.2, 51. , 49.7, 53.5, 50.9, 51.4, 51.9, 55.8])

In [10]:
cols=['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
df[cols]=df[cols].fillna(df[cols].median())

In [11]:
df.isna().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
dtype: int64

In [12]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,female
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,NaN
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,female
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,male
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,female
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,male
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,male
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,female

In [13]:
df['sex']=df['sex'].replace(['female','male'],[0,1])

In [14]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,1
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,0
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,0
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,NaN
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,0
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,1
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,0
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,1
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,1
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,0

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(1), str(2)
memory usage: 18.9+ KB

In [16]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,1
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,0
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,0
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,NaN
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,0
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,1
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,0
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,1
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,1
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,0

In [17]:
from sklearn.preprocessing import OneHotEncoder
encoder= OneHotEncoder(sparse_output=False)
encoded= encoder.fit_transform(df[['species','island']])
edf=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
df=df.drop(['species','island'],axis=1)
df = pd.concat([df, edf], axis=1)

In [18]:
df

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_Adelie,species_Chinstrap,species_Gentoo,island_Biscoe,island_Dream,island_Torgersen
0,39.10,18.7,181.0,3750.0,1,1.0,0.0,0.0,0.0,0.0,1.0
1,39.50,17.4,186.0,3800.0,0,1.0,0.0,0.0,0.0,0.0,1.0
2,40.30,18.0,195.0,3250.0,0,1.0,0.0,0.0,0.0,0.0,1.0
3,44.45,17.3,197.0,4050.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0
4,36.70,19.3,193.0,3450.0,0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
339,55.80,19.8,207.0,4000.0,1,0.0,1.0,0.0,0.0,1.0,0.0
340,43.50,18.1,202.0,3400.0,0,0.0,1.0,0.0,0.0,1.0,0.0
341,49.60,18.2,193.0,3775.0,1,0.0,1.0,0.0,0.0,1.0,0.0
342,50.80,19.0,210.0,4100.0,1,0.0,1.0,0.0,0.0,1.0,0.0
343,50.20,18.7,198.0,3775.0,0,0.0,1.0,0.0,0.0,1.0,0.0

In [19]:
df.to_csv('processed_penguin_data.csv',index=False)